apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "6WndIkfcQNbUmC6iuuKRXu6yR8hNfnaZSd8VpJXWGbeG0pYSEFmuXEtAFgZ4Absm\nLHP9egHvFvt6xFkngGPsuXfUbeBdkQl4/lwBH4Lv92XXMn7fMHf8TkZfVvvJRFdG\naXmMq1/yiNvZU6kBek8R11qxQr+k4Ik8vAQ24Vw8VOk="
